services:
  bot:
    container_name: listify
    image: ghcr.io/evgeny1101/listify:v1.4.1
    restart: unless-stopped
    volumes:
      - ./listify.db:/app/listify.db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - NOTIFICATION_TIME=${NOTIFICATION_TIME:-}
      - DEFAULT_TZ_OFFSET=${DEFAULT_TZ_OFFSET:-3}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"